tank_drive_controller:
  ros__parameters:
    front_wheel_diameter: 0.230   # in meters 
    rear_wheel_diameter: 0.280 # in meters
    wheel_separation: 0.515 # in meters
    wheel_base: 0.700 # in meters
    max_linear_velocity: 1.0 # in m/s
    max_angular_velocity: 2.0 # in rad/s
    max_linear_acceleration: 1.0 # in m/s^2
    max_angular_acceleration: 1.5 # in rad/s^2
    odom_frequency: 50 # in Hz
    motor_command_frequency: 50 # in Hz
    publish_tf: true


    use_pid: true
    # Linear velocity PID parameters
    linear_pid_kp: 0.00
    linear_pid_ki: 0.01
    linear_pid_kd: 0.00
    linear_pid_windup_limit: 3.0

    # Angular velocity PID parameters
    angular_pid_kp: 0.00
    angular_pid_ki: 0.01
    angular_pid_kd: 0.00
    angular_pid_windup_limit: 3.0