tank_drive_controller:
  ros__parameters:
    front_wheel_diameter: 0.186
    rear_wheel_diameter: 0.148
    wheel_separation: 0.515
    wheel_base: 0.700
    max_linear_velocity: 1.0
    max_angular_velocity: 2.0
    max_linear_acceleration: 1.0
    max_angular_acceleration: 1.5
    odom_frequency: 50
    motor_command_frequency: 50
    publish_tf: true


    use_pid: true
    # Linear velocity PID parameters
    linear_pid_kp: 0.05
    linear_pid_ki: 0.01
    linear_pid_kd: 0.01
    linear_pid_windup_limit: 0.3

    # Angular velocity PID parameters
    angular_pid_kp: 0.05
    angular_pid_ki: 0.01
    angular_pid_kd: 0.01
    angular_pid_windup_limit: 0.5